sudo: false
language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - pypy

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

addons:
    apt_packages:
        - binutils
        - default-jdk
        - gdal-bin
        - libgdal1h
        - libgeos-c1
        - libproj-dev
        - libxapian22
        - python-xapian
        - wajig

before_install:
    - mkdir -p $HOME/download-cache

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install mock==1.0.1; fi
    - pip install requests "Django${DJANGO_VERSION}"
    - python setup.py clean build install

before_script:
    - BACKGROUND_SOLR=true test_haystack/solr_tests/server/start-solr-test-server.sh

script:
    - python test_haystack/solr_tests/server/wait-for-solr
    - SOLR_SCHEMA="test_haystack/solr_tests/server/solr4/solr/collection1/conf/schema.xml" python setup.py test

env:
    matrix:
        - DJANGO_VERSION=">=1.6,<1.7"
        - DJANGO_VERSION=">=1.7,<1.8"
        - DJANGO_VERSION=">=1.8,<1.9"
        - SOLR_VERSION="4.10.4"
        - SOLR_VERSION="5.2.1"

matrix:
    allow_failures:
        - python: "pypy"
        - python: 2.6
    exclude:
       - python: 2.6
         env: DJANGO_VERSION=">=1.7,<1.8"
       - python: 2.6
         env: DJANGO_VERSION=">=1.8,<1.9"

services:
    - elasticsearch

notifications:
    irc: "irc.freenode.org#haystack"
    email: false
