sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

addons:
    apt_packages:
        - binutils
        - default-jdk
        - gdal-bin
        - libgdal1h
        - libgeos-c1
        - libproj-dev
        - libxapian22
        - python-xapian
        - wajig

before_install:
    - mkdir -p $HOME/download-cache
    - >
      if [[ $VERSION_ES == '>=2.0.0,<3.0.0' ]];
      then
        wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.1/elasticsearch-2.2.1.tar.gz
        tar zxf elasticsearch-2.2.1.tar.gz
        elasticsearch-2.2.1/bin/elasticsearch -d -Dhttp.port=9200
      else
        wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.5.tar.gz
        tar zxf elasticsearch-1.7.5.tar.gz
        elasticsearch-1.7.5/bin/elasticsearch -d -Dhttp.port=9200
      fi

install:
    - pip install requests "Django${DJANGO_VERSION}" "elasticsearch${VERSION_ES}"
    - python setup.py clean build install

before_script:
    - BACKGROUND_SOLR=true test_haystack/solr_tests/server/start-solr-test-server.sh

script:
    - python test_haystack/solr_tests/server/wait-for-solr
    - python setup.py test

env:
    matrix:
        - DJANGO_VERSION=">=1.8,<1.9" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=1.9,<1.10" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=1.8,<1.9" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=1.9,<1.10" VERSION_ES=">=2.0.0,<3.0.0"

matrix:
    allow_failures:
        - python: "pypy"

notifications:
    irc: "irc.freenode.org#haystack"
    email: false
