language: python
python:
  - "2.7"

cache:
  directories:
    - test_haystack/solr_tests/server/
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE
  - sudo apt-get update
  - sudo apt-get install wajig binutils gdal-bin libproj-dev libgeos-c1 libgdal1h libxapian22 python-xapian default-jdk

install:
  - pip install tox requests
  - pip install -e .

before_script:
  - BACKGROUND_SOLR=true test_haystack/solr_tests/server/start-solr-test-server.sh

script:
  - tox -e $TOX_ENV

env:
  global:
      - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
      - TOX_ENV=py26-django1.5
      - TOX_ENV=py26-django1.6
      - TOX_ENV=py27-django1.5
      - TOX_ENV=py27-django1.6
      - TOX_ENV=py27-django1.7
      - TOX_ENV=py33-django1.5
      - TOX_ENV=py33-django1.6
      - TOX_ENV=py33-django1.7
      - TOX_ENV=py34-django1.5
      - TOX_ENV=py34-django1.6
      - TOX_ENV=pypy-django1.5
      - TOX_ENV=pypy-django1.6
      - TOX_ENV=pypy-django1.7

services:
  - elasticsearch

notifications:
  irc: "irc.freenode.org#haystack"
  email: false
